FROM node:20.11-alpine3.19

# 1) Install psql (PostgreSQL client)
RUN apk add --no-cache postgresql-client

# 2) Set workdir and install app deps
WORKDIR /app
COPY package*.json ./
COPY prisma ./
RUN npm install

# Generate Prisma client BEFORE copying the rest of the code
RUN npx prisma generate

# 3) Copy the rest of your code
COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev"]